module.exports = {
    future: {
        removeDeprecatedGapUtilities: true,
        purgeLayersByDefault: true,
    },
    purge: {
        content: ['./components/**/*.{js,ts,jsx,tsx}', './pages/**/*.{js,ts,jsx,tsx}'],
    },
    theme: {
        fontSize: {
            xs: '.75rem',
            sm: '.875rem',
            tiny: '.875rem',
            base: '1rem',
            lg: '1.125rem',
            xl: '1.25rem',
            '2xl': '1.5rem',
            '3xl': '1.875rem',
            '4xl': '2.25rem',
            '5xl': '2.5rem',
            '6xl': '2.75rem',
            '7xl': '3rem',
            '8xl': '3.5rem',
            '9xl': '4rem',
            '10xl': '5rem',
            '20xl': '15rem',
            '21xl': '17rem',
            '22xl': '20rem',
            '12Lg': '12.5px',
            13: '13px',
            14: '14px',
            15: '15px',
        },
        backgroundColor: (theme) => ({
            ...theme('colors'),
            'indigo-1000': '#18153a',
            orange: '#ff7a59',
            error: '#DC4B5C44',
            modal: '#00000044',
            primary: '#582DE8',
            'ss-primary-o-200': '#582DE844',
            'ss-primary-o-400': '#582DE8BB',
            primaryHover: '#4022ad',
            secondary: '#c0d3dd',
            secondaryHover: '#9fb7c4',
            ssWhite: '#f2f2f2',
            ssWhite2: '#fafafa',
            ssLightgreen: '#faffee',
            ssLightblue: '#EEF3F4',
            ssLightblue2: '#ecf1f4',
            ssLightblue3: '#e8eef2',
            ssLightblue4: '#EFF5F9',
            ssLightblue5: '#C0D3DD',
            ssLightblue6: '#E8EEF2',
            ssLightblue7: '#1db3d3',
            ssLightblue8: '#2AAAE1',
            ssGray: '#595959',
            ssGray2: '#4d4d4d',
            ssGray3: '#d0dae0',
            ssBlue: '#1067d7',
            ssGreen: '#9ED100',
            ssPurple: '#ab29d5',
            ssYellow: '#f2b42a',
            react: '#29ABE2',
        }),
        textColor: (theme) => ({
            ...theme('colors'),
            primary: '#582DE8',
            secondary: '#390094',
            error: '#DC4B5C',
            error2: '#721c24',
            success: '#64a864',
            success2: '#00A99D',
            react: '#29ABE2',
            ssLightblue2: '#1db3d3',
            ssBlueGray: '#b9d4de',
            ssBlueGray2: '#51677c',
            ssBlueGray3: '#4B5E6B',
            ssGray: '#A3A3A3',
            ssGray2: '#5B5B5B',
            ssGray3: '#4d4d4d',
            ssGray4: '#3B3B3B',
            ssGray5: '#A2AbAf',
            ssBlue: '#1067d7',
            ssGreen: '#9ED100',
            ssPurple: '#ab29d5',
            ssYellow: '#f2b42a',
            tailwind: '#319795',
        }),
        borderColor: (theme) => ({
            ...theme('colors'),
            'indigo-1000': '#18153a',
            primary: '#582DE8',
            secondary: '#390094',
            modal: '#00000088',
            ssGrayDark: '#4D6073',
            ssLightBlue: '#BCCFD9',
            ssLightGray: '#E5E5E5',
            ssLightGray2: '#D5D5D5',
            ssLightblue3: '#1db3d3',
            ssBlue: '#1067d7',
            ssGreen: '#9ED100',
            ssPurple: '#ab29d5',
            ssYellow: '#f2b42a',
            react: '#29ABE2',
        }),
        boxShadow: {
            simple: '0px 3px 10px rgba(75, 94, 107, 0.3)',
            marked: '0px 0px 20px rgba(0, 0, 0, 0.1)',
        },
        screens: {
            mobileXs: '350px',
            mobileSm: '420px',
            mobile: '520px',
            mobileLg: '600px',
            tablet: '762px',
            tabletLg: '880px',
            tabletXl: '952px',
            laptop: '1024px',
            laptopLg: '1160px',
            desktop: '1396px',
        },
        extend: {
            width: {
                97: '97%',
            },
            height: {
                72: '20rem',
            },
            minHeight: {
                'extra-screen': '120vh',
            },
        },
    },
    variants: {},
    plugins: [],
};
