module.exports = {
    future: {
        removeDeprecatedGapUtilities: true,
        purgeLayersByDefault: true,
    },
    purge: {
        content: ['./components/**/*.{js,ts,jsx,tsx}', './pages/**/*.{js,ts,jsx,tsx}'],
    },
    theme: {
        fontSize: {
            xs: '.75rem',
            sm: '.875rem',
            tiny: '.875rem',
            base: '1rem',
            lg: '1.125rem',
            xl: '1.25rem',
            '2xl': '1.5rem',
            '3xl': '1.875rem',
            '4xl': '2.25rem',
            '5xl': '2.5rem',
            '6xl': '2.75rem',
            '7xl': '3rem',
            '8xl': '3.5rem',
            '9xl': '4rem',
            '10xl': '5rem',
        },
        backgroundColor: (theme) => ({
            ...theme('colors'),
            'indigo-1000': '#18153a',
            'custom-purple': '#582DE8',
            'custom-purple-900': '#4022ad',
            'custom-yellow': '#f2b42a',
            orange: '#ff7a59',
            modal: '#00000044',
            react: '#29ABE2',
        }),
        textColor: (theme) => ({
            ...theme('colors'),
            'custom-purple': '#582DE8',
            'custom-yellow': '#f2b42a',
            react: '#29ABE2',
            tailwind: '#319795',
            orange: '#ff7a59',
        }),
        borderColor: (theme) => ({
            ...theme('colors'),
            'custom-purple': '#582DE8',
            'custom-yellow': '#f2b42a',
            react: '#29ABE2',
            orange: '#ff7a59',
        }),
        boxShadow: {
            simple: '0px 3px 10px rgba(75, 94, 107, 0.3)',
            marked: '0px 0px 20px rgba(0, 0, 0, 0.1)',
        },
        screens: {
            mobileXs: '350px',
            mobileSm: '420px',
            mobile: '520px',
            mobileLg: '600px',
            tablet: '762px',
            tabletLg: '880px',
            tabletXl: '952px',
            laptop: '1024px',
            laptopLg: '1160px',
            desktop: '1396px',
        },
        extend: {
            width: {
                97: '97%',
            },
            height: {
                72: '20rem',
            },
            minHeight: {
                'extra-screen': '120vh',
            },
        },
    },
    variants: {},
    plugins: [],
};
